### ISSUE TITLE
No magic.shape_inference.utils file

### ISSUE THREAD

**Issue by xinyusun1997** [babbatem/GeneralizingKinematics#1]
Hi, when I tried to run the codes, I found that there is no magic.shape_inference.utils file here (I guess the expand_labels function may be in it).
Could you please help me to check the above issue?

**Comment by babbatem** [comment]
Hey, sorry about that, pull again and you should be good. 
That functionality is in magic.mixture.utils, I had forgotten to change the import statement. 
Thanks for trying things! Let me know if you have other issues.
